# Generated by Django 3.2.25 on 2024-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svm_acc', models.CharField(max_length=100)),
                ('rfc_acc', models.CharField(max_length=100)),
                ('gbc_acc', models.CharField(max_length=100)),
                ('dnn_bert_acc', models.CharField(max_length=100)),
            ],
        ),
    ]
